"""Render the placeholder film into the site's frame folders and write
film/manifest.js. Resumable: frames already on disk are kept."""
import os, sys, json, time, shutil
import numpy as np
from PIL import Image
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from kit import finish, to_image
import scene_gopuram as A, scene_corridor as B, scene_courtyard as C, scene_mandapam as D

SITE = sys.argv[1] if len(sys.argv) > 1 else os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
FILM = os.path.join(SITE, 'film')
VARIANTS = [('desktop', 1280, 720, 70), ('mobile', 576, 1024, 72)]
SCENES = [(A, 60), (B, 60), (C, 44), (D, 60)]
OVER = 8                      # frames of cross-dissolve between scenes
ANCHORS = [(0, 0.08), (1, 0.32), (1, 0.72), (2, 0.6), (3, 0.55), (3, 0.985)]

starts, s = [], 0
for m, n in SCENES:
    starts.append(s)
    s += n - OVER
N = starts[-1] + SCENES[-1][1]
CHAPTERS = [int(round(starts[i] + u * (SCENES[i][1] - 1))) for i, u in ANCHORS]


def smooth(t):
    t = min(1.0, max(0.0, t))
    return t * t * (3 - 2 * t)


def frame_px(f, W, H):
    live = [(i, m, (f - starts[i]) / (n - 1)) for i, (m, n) in enumerate(SCENES) if 0 <= f - starts[i] < n]
    if len(live) == 1:
        return live[0][1].render(live[0][2], W, H)
    (i0, m0, u0), (i1, m1, u1) = live[:2]
    w = smooth((f - starts[i1] + 0.5) / OVER)
    return m0.render(u0, W, H) * (1 - w) + m1.render(u1, W, H) * w


def lum_of(im):
    a = np.asarray(im.resize((64, 64)), np.float32) / 255.0
    b = a[18:38, 12:52]       # the band the copy sits in
    return float((b[..., 0] * 0.2126 + b[..., 1] * 0.7152 + b[..., 2] * 0.0722).mean())


def main():
    for name, *_ in VARIANTS:
        os.makedirs(os.path.join(FILM, name), exist_ok=True)
    os.makedirs(os.path.join(FILM, 'stills'), exist_ok=True)
    lums = {v[0]: [0.0] * N for v in VARIANTS}
    t0 = time.time()
    for f in range(N):
        for name, W, H, q in VARIANTS:
            path = os.path.join(FILM, name, '%03d.webp' % f)
            if os.path.exists(path):
                im = Image.open(path).convert('RGB')
            else:
                im = to_image(finish(frame_px(f, W, H), f, grain=0.008, vignette=0.24))
                im.save(path, 'WEBP', quality=q, method=4)
            lums[name][f] = round(lum_of(im), 3)
        print('frame', f + 1, '/', N, round(time.time() - t0), 's', flush=True)
    for name, W, H, q in VARIANTS:
        for k, a in enumerate(CHAPTERS):
            shutil.copy(os.path.join(FILM, name, '%03d.webp' % a), os.path.join(FILM, 'stills', '%s-%d.webp' % (name, k + 1)))
        Image.open(os.path.join(FILM, name, '%03d.webp' % CHAPTERS[0])).convert('RGB').save(
            os.path.join(FILM, 'poster-%s.jpg' % name), quality=82)
    og = Image.open(os.path.join(FILM, 'desktop', '%03d.webp' % CHAPTERS[0])).convert('RGB').resize((1200, 675), Image.LANCZOS)
    og.crop((0, 22, 1200, 652)).save(os.path.join(FILM, 'og.jpg'), quality=84)
    man = {'frames': N, 'pad': 3, 'ext': 'webp', 'chapters': CHAPTERS,
           'variants': {name: {'w': W, 'h': H, 'dir': 'film/' + name, 'lum': lums[name]} for name, W, H, q in VARIANTS}}
    with open(os.path.join(FILM, 'manifest.js'), 'w') as fh:
        fh.write('/* Generated by the film builder. frames/chapters/lum describe the cut. */\n')
        fh.write('window.FILM = ' + json.dumps(man, separators=(',', ':')) + ';\n')
    # review sheet (not shipped)
    th = [Image.open(os.path.join(FILM, 'desktop', '%03d.webp' % f)).resize((256, 144)) for f in range(0, N, 8)]
    cols = 5
    sheet = Image.new('RGB', (cols * 260, ((len(th) + cols - 1) // cols) * 148), (16, 16, 16))
    for i, t in enumerate(th):
        sheet.paste(t, ((i % cols) * 260, (i // cols) * 148))
    sheet.save(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'film_sheet.png'))
    print('DONE', N, CHAPTERS, flush=True)


if __name__ == '__main__':
    main()
